name: CI

on:
  pull_request:
    branchs:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4 

      - name: setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: check format
        run: npm run format

      - name: check lint
        run: npm run lint
      
      - name: Build
        run: npm run build

      # - name: Test
      #   run: npm run test

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: dist
      #     path: dist
